### ISSUE TITLE
Update version 1.0.5

### ISSUE THREAD

**Issue by tvd12** [youngmonkeys/game-box#15]
[ x ] 1. Thêm hàm maxPlayer vào MMORoom.Builder
[ x ] 2. Thêm trường master vào MMORoom
~~[   ] 3. playerManager, roomManager cho MMOVirtualWorld~~ --> ~~globalPlayerManager, globalRoomManager~~ --> Issue https://github.com/youngmonkeys/game-box/issues/20
[ x ] 4. Sửa lại [MMORoomGroup.sleep](https://github.com/youngmonkeys/game-box/blob/master/src/main/java/com/tvd12/gamebox/entity/MMORoomGroup.java#L38) phải tính khoảng sleep time còn lại thay vì sleep đúng bằng time tick. Vì nếu việc tính toán chậm sẽ làm delay tích tụ dần
[ x ] 5. Bổ sung clientTimeTick vào MMOPlayer
~~[   ] 6. Xem xét xem có cách nào để làm logic tìm room master của LocatedRoom đơn giản hơn không~~ --> Issue https://github.com/youngmonkeys/game-box/issues/21
[ x ] 7. Bổ sung các vector đơn vị Vec3.left, Vec3.right, Vec3.up, Vec3.down
[ x ] 8. final private List nearbyPlayerNamesBuffer

**Comment by tvd12** [comment]
final private List<String> nearbyPlayerNamesBuffer

**Comment by vu-luong** [comment]
> final private List nearbyPlayerNamesBuffer

Cái này là sao anh nhỉ?

**Comment by tvd12** [comment]
> > final private List nearbyPlayerNamesBuffer
> 
> Cái này là sao anh nhỉ?

Là do mình quên ko để final, trong file này em ạ: https://github.com/youngmonkeys/game-box/blob/master/src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java

**Comment by vu-luong** [comment]
@tvd12 Em thấy phải có 1 cái playerManager cho MMOVirtualWorld. Ví dụ khi user thoát app, dev chỉ cần gọi mmoVirtualWorld.remove(player), nó sẽ tự tìm phòng tương ứng và xóa player khỏi phòng đó

**Comment by tvd12** [comment]
> @tvd12 Em thấy phải có 1 cái `playerManager` cho `MMOVirtualWorld`. Ví dụ khi user thoát app, dev chỉ cần gọi `mmoVirtualWorld.remove(player)`, nó sẽ tự tìm phòng tương ứng và xóa player khỏi phòng đó

anh thấy hợp lý em ạ

**Comment by vu-luong** [comment]
@tvd12 Em nghĩ sau khi mình thảo luận chốt feature anh nên edit cái list ở comment đầu tiên, sau xem lại cho dễ đỡ phải lướt comments anh ạ.

**Comment by tvd12** [comment]
> @tvd12 Em nghĩ sau khi mình thảo luận chốt feature anh nên edit cái list ở comment đầu tiên, sau xem lại cho dễ đỡ phải lướt comments anh ạ.

ok em, anh vừa update rồi nhé

**Comment by vu-luong** [comment]
Mình phải thêm `roomManager` cho MMOVirtualWorld nữa anh ạ. Em muốn lấy list các room của MMOVirtualWorld mà hiện tại phải dựa vào cái globalRoomManager
