### ISSUE TITLE
SyncPositionRoomUpdatedHandler

### ISSUE THREAD

**Issue by vu-luong** [youngmonkeys/game-box#5]
# Mô tả
* Tự động sync position sau khi room updated nếu dev không có ý kiến gì

# Cài đặt
## SyncPositionRoomUpdatedHandler
* Tạo lớp SyncPositionRoomUpdatedHandler extends MMORoomUpdateHandler, implement method onRoomUpdated
```java
@Override
public void onRoomUpdated(MMORoom room) {
      for each player in room:
            responseFactory.newArrayResponse()
                  .command(Commands.SYNC_POSITION)
                  .data(player.getPosition())
                  .usernames(nearbyPlayers) // chỉ gửi request đến những thằng nearby
                  .execute();
}
```

# Viết test
* Viết các lớp unitest tương ứng

# Câu hỏi
* Làm sao để thằng SyncPositionRoomUpdatedHandler là mặc định?

**Comment by tvd12** [comment]
@vu-luong 
Ko phải request mà là vị trí của player đang được loop em ạ, kiểu là em lấy chính vị trí của em gửi cho những thằng khác ấy em, khả năng mình cần 1 biến để đánh dấu là vị trí đã bị change hay chưa để hạn chế gửi dữ liệu đến client em ạ

**Comment by vu-luong** [comment]
Em sửa lại như này ổn không anh:

```java
public class SyncPositionRoomUpdatedHandler implements MMORoomUpdateHandler {

      private Map<String, Vec3> currentPositions = new ConcurrentHashMap<>();
      List<String> nearbyPlayersBuffer = new ArrayList<>();
      
      @Override
      public void onRoomUpdated(MMORoom room) {
            for each player in room {
                  Vec3 currentPosition = currentPositions.get(player.getName());
                  Vec3 newPosition = player.getPosition();

                  // Kiểm tra xem position có thay đổi ko
                  if (!newPosition.equals(currentPosition)) {
                        currentPositions.replace(player.getName(), newPosition);

                        nearbyPlayersBuffer.clear();
                        player.getNearbyPlayerNames(nearbyPlayersBuffer);

                        responseFactory.newArrayResponse()
                              .command(Commands.SYNC_POSITION)
                              .data(newPosition)
                              .usernames(nearbyPlayersBuffer)
                              .execute();
                  }
            }
      }   
}
```

**Comment by tvd12** [comment]
Anh nghĩ dùng 1 biến AtomicBoolean là đủ em ạ, lúc gọi hàm set position và set rotation thì set cái biến đó là true, lúc sync xong thì set là false em ạ, à chỗ sync position phải có cả rotation em nhé

**Comment by vu-luong** [comment]
AtomicBoolean khác gì với volatile boolean vậy anh?

**Comment by vu-luong** [comment]
Mình chỉ sync position mỗi khi player gửi request lên, hay cứ mỗi 100ms gọi sync 1 lần anh nhỉ?

**Comment by tvd12** [comment]
> AtomicBoolean khác gì với volatile boolean vậy anh?

anh trả lời ở đây nhé: https://stackask.com/question/volatile-boolean-khac-gi-atomicboolean/#comments

**Comment by tvd12** [comment]
> Mình chỉ sync position mỗi khi player gửi request lên, hay cứ mỗi 100ms gọi sync 1 lần anh nhỉ?

mình sync mỗi `100ms` em nhé, à mà cái này em để là 1 biến set nhé

**Comment by tvd12** [comment]
thằng responseFactory nó không hiểu thằng `player.getPosiion()` đâu em ạ, em bổ sung hàm `public EzyArray toArray` vào nhé:

```java
package com.tvd12.gamebox.util;

import com.tvd12.ezyfox.entity.EzyArray;
import com.tvd12.ezyfox.factory.EzyEntityFactory;
import com.tvd12.gamebox.math.Vec3;

public final class Vec3s {
	
	private Vec3s() {}
	
	public static EzyArray toArray(Vec3 value) {
		EzyArray array = EzyEntityFactory.newArray();
		array.add(value.getX());
		array.add(value.getY());
		array.add(value.getZ());
		return array;
	}
}

```

**Comment by tvd12** [comment]
Còn chỗ sync sẽ kiểu:

```java
@Override
public void onRoomUpdated(MMORoom room) {
      for each player in room:
            responseFactory.newArrayResponse()
                  .command(Commands.SYNC_POSITION)
                  . append(Vec3s.toArray(player.getPosition()))
                  . append(Vec3s.toArray(player.getRotation()))
                  .usernames(nearbyPlayers) // chỉ gửi request đến những thằng nearby
                  .execute();
}
```

**Comment by vu-luong** [comment]
> thằng responseFactory nó không hiểu thằng `player.getPosiion()` đâu em ạ, em bổ sung hàm `public EzyArray toArray` vào nhé:
> 
> ```java
> package com.tvd12.gamebox.util;
> 
> import com.tvd12.ezyfox.entity.EzyArray;
> import com.tvd12.ezyfox.factory.EzyEntityFactory;
> import com.tvd12.gamebox.math.Vec3;
> 
> public final class Vec3s {
> 	
> 	private Vec3s() {}
> 	
> 	public static EzyArray toArray(Vec3 value) {
> 		EzyArray array = EzyEntityFactory.newArray();
> 		array.add(value.getX());
> 		array.add(value.getY());
> 		array.add(value.getZ());
> 		return array;
> 	}
> }
> ```

Vậy em dùng `EzyEntityFactory.newObjectBuilder()` thay vì phải tạo array được không anh? Với lại có phải broadcast cả thằng `player.getName()` không anh nhỉ?

**Comment by tvd12** [comment]
Có em ạ, em dùng hàm append, nó có sẵn hàm append em ạ, nó tự tạo array ở bên trong cho em em ạ

**Comment by vu-luong** [comment]
> Anh nghĩ dùng 1 biến AtomicBoolean là đủ em ạ, lúc gọi hàm set position và set rotation thì set cái biến đó là true, lúc sync xong thì set là false em ạ, à chỗ sync position phải có cả rotation em nhé

Nếu chỉ dùng AtomicBoolean như này em nghĩ không ổn anh ạ. Nếu lúc sync xong set lại là `false`, thì lần sau vào `onRoomUpdated` nó lại gọi sync tiếp, vậy lần nào mình cũng phải sync --> số lần gửi request không giảm

**Comment by tvd12** [comment]
em đặt tên biến là positionChanged, vậy khi thằng user nó gửi position lên server thì ở cái hàm setPosition và setRotation nó sẽ kiểu:

```java
public void setPosition(double x, double y, double z) {
  ... x, y ,x = 
  this.positionChanged = true;
}
```

đến chỗ mà em gửi vị trí cho client thì em gọi cái hàm setPositionChange(false) là được em ạ
